### ISSUE TITLE
Can you share the `vim.g.clipboard` definition you would use for this tool?

### ISSUE THREAD

**Issue by waydegilliam** [rumpelsepp/oscclip#20]

**Comment by rumpelsepp** [comment]
I am not sure if this actually works. I tried it once and I got errors that `oscclip` does not find the terminal device. Maybe I am missing something.

**Comment by rumpelsepp** [comment]
I take the liberty to close this in favor of (upcoming) native support in neovim: https://github.com/neovim/neovim/pull/25872

**Comment by rumpelsepp** [comment]
For reference: https://github.com/neovim/neovim/blob/cd31a72f9b22741c6ece1c47a91d990e2df218fa/runtime/doc/provider.txt#L257-L284

You could use this with:

``` lua
    vim.g.clipboard = {
      name = 'OSC 52',
      copy = {
        ['+'] = require('vim.clipboard.osc52').copy,
        ['*'] = require('vim.clipboard.osc52').copy,
      },
      paste = {
        ['+'] = require('vim.clipboard.osc52').paste,
        ['*'] = require('vim.clipboard.osc52').paste,
      },
    }
```
